SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_LIBRARY_ARCHITECTURE $ENV{CROSS_TRIPLE})

SET(CMAKE_C_COMPILER $ENV{CC})
SET(CMAKE_CXX_COMPILER $ENV{CXX})

SET(PKG_CONFIG_EXECUTABLE /usr/bin/$ENV{CROSS_TRIPLE}-pkg-config)
SET(PKGCONFIG_EXECUTABLE /usr/bin/$ENV{CROSS_TRIPLE}-pkg-config)
